chore(release): prepare for v0.6.0 (#2075)
## Why this should be merged

Bumps from v0.5.0 to v0.6.0.

## How this works

Followed instructions in `RELEASE.md`.

*Note*: any attempt to bump the Rust dependencies in this version failed
as any bump would move `generic-array` from `0.14.7` to `0.14.9`,
triggering a API deprecated error that would be caught by CI commands
such as `cargo clippy --locked --features ethhash,logger --workspace
--all-targets -- -D warnings`:

```
error: use of deprecated struct `sha3::digest::generic_array::GenericArray`: please upgrade to generic-array 1.x
   --> storage/src/hashtype/trie_hash.rs:6:34
    |
  6 | use sha2::digest::generic_array::GenericArray;
    |                                  ^^^^^^^^^^^^
    |
    = note: `-D deprecated` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(deprecated)]`

  error: use of deprecated struct `sha3::digest::generic_array::GenericArray`: please upgrade to generic-array 1.x
    --> storage/src/hashtype/trie_hash.rs:92:11
     |
  92 | impl From<GenericArray<u8, typenum::U32>> for TrieHash {
     |           ^^^^^^^^^^^^

  error: use of deprecated struct `sha3::digest::generic_array::GenericArray`: please upgrade to generic-array 1.x
    --> storage/src/hashtype/trie_hash.rs:93:20
     |
  93 |     fn from(value: GenericArray<u8, typenum::U32>) -> Self {
     |                    ^^^^^^^^^^^^

  error: use of deprecated method `sha3::digest::generic_array::GenericArray::<T, N>::as_slice`: please upgrade to generic-array 1.x
     --> storage/src/hashers/ethhash.rs:162:79
      |
  162 |                     .and_then(|bytes| replace_list_field(bytes, 2, empty_root.as_slice()).ok())
      |                                                                               ^^^^^^^^

  error: use of deprecated method `sha3::digest::generic_array::GenericArray::<T, N>::as_slice`: please upgrade to generic-array 1.x
     --> storage/src/hashers/ethhash.rs:263:53
      |
  263 |                         RlpItem::Bytes(hashed_bytes.as_slice()),
      |                                                     ^^^^^^^^

  error: use of deprecated method `sha3::digest::generic_array::GenericArray::<T, N>::as_slice`: please upgrade to generic-array 1.x
    --> storage/src/hashtype/ethhash.rs:64:64
     |
  64 |             HashOrRlp::Rlp(r) => Keccak256::digest(r.as_ref()).as_slice() == other.as_ref(),
     |                                                                ^^^^^^^^

  error: use of deprecated method `sha3::digest::generic_array::GenericArray::<T, N>::as_slice`: please upgrade to generic-array 1.x
    --> storage/src/hashtype/ethhash.rs:73:64
     |
  73 |             HashOrRlp::Rlp(r) => Keccak256::digest(r.as_ref()).as_slice() == self.as_ref(),
     |                                                                ^^^^^^^^

  error: use of deprecated method `sha3::digest::generic_array::GenericArray::<T, N>::as_slice`: please upgrade to generic-array 1.x
    --> storage/src/hashtype/ethhash.rs:88:38
     |
  88 |                 Keccak256::digest(r).as_slice() == h.as_ref()
     |                                      ^^^^^^^^

  error: could not compile `firewood-storage` (lib) due to 8 previous errors
  warning: build failed, waiting for other jobs to finish...
  error: could not compile `firewood-storage` (lib test) due to 8 previous errors
```

Given that we shouldn't manually fix any dependencies bumps when
releasing a new version, I went ahead and just bumped the versioning for
each crate.

## How this was tested

CI

## Breaking Changes

- [ ] firewood
- [ ] firewood-storage
- [ ] firewood-ffi (C api)
- [ ] firewood-go (Go api)
- [ ] fwdctl